"""snake case to camel case

Revision ID: 3541e017316f
Revises: fcff0f716ebd
Create Date: 2025-01-15 16:11:24.583178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3541e017316f'
down_revision = 'fcff0f716ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passwordHash', sa.String(length=256), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=256), nullable=False))
        batch_op.drop_column('passwordHash')

    # ### end Alembic commands ###
